name: Full AWS Deploy (ECR + CloudFormation)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # 1. Checkout Code
      # ------------------------
      - name: Checkout Code
        uses: actions/checkout@v3

      # ------------------------
      # 2. Configure AWS
      # ------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # ------------------------
      # 3. Login to ECR
      # ------------------------
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin \
          $891377043411.dkr.ecr.us-east-1.amazonaws.com

      # ------------------------
      # 4. Build Docker Image
      # ------------------------
      - name: Build Docker Image
        run: docker build -t carbon-backend .

      # ------------------------
      # 5. Tag Docker Image
      # ------------------------
      - name: Tag Docker Image
        run: |
          docker tag carbon-backend:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/carbon-backend:latest

      # ------------------------
      # 6. Push to ECR
      # ------------------------
      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/carbon-backend:latest

      # ------------------------
      # 7. Deploy CloudFormation
      # ------------------------
      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: CarbonFootprintStack
          template: template.yml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
