name: AWS Deploy Stack
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-2

      - name: Deploy to CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: CarbonFootprintStack
          template: src/infra/template.yml
          no-fail-on-empty-changeset: "1" # FIXES THE 255 ERROR
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: |
            StudentNumber=${{ secrets.STUDENT_ID }},
            BackendImage=public.ecr.aws/docker/library/node:latest
